
###########################################################################
#             This file is generated by RCH/CapistranoBundle              #
#                                                                         #
#               https://github.com/chalasr/CapistranoBundle               #
#                  Robin Chalas <robin.chalas@gmail.com>                  #
#                                                                         #
###########################################################################

# Production
server 'rch.fr',
user: 'chalasr',
ssh_options: {
    user: 'chalasr',
    keys: %w(/home/ssh_user/.ssh/id_rsa),
    forward_agent: false,
    auth_methods: %w(publickey password),
}

set(:deploy_to, '/var/www/html')