<?php

/**
 * This file is part of RCH/CapistranoBundle.
 *
 * Robin Chalas <robin.chalas@gmail.com>
 *
 * For more informations about license, please see the LICENSE
 * file distributed in this source code.
 */

namespace RCH\CapistranoBundle\Test\Generator;

use RCH\CapistranoBundle\Generator\GeneratorInterface;
use RCH\CapistranoBundle\Generator\YamlStagingGenerator;

/**
 * Tests the StagingGenerator.
 *
 * @author Robin Chalas <robin.chalas@gmail.com>
 */
class YamlStagingGeneratorTest extends \PHPUnit_Framework_TestCase
{
    /** @var string */
    protected $path;

    /** @var string */
    protected $name;

    /** @var array */
    protected $params;

    /** @var string */
    protected $expected = "
###########################################################################
#             This file is generated by RCH/CapistranoBundle              #
#                                                                         #
#               https://github.com/chalasr/CapistranoBundle               #
#                  Robin Chalas <robin.chalas@gmail.com>                  #
#                                                                         #
###########################################################################

domain: 'rch.fr'
user: 'chalasr'
keys: '/home/ssh_user/.ssh/id_rsa'
forward_agent: 'false'
auth_methods: 'publickey password'
deploy_to: '/var/www/html'
";

    public function setUp()
    {
        $this->path = sys_get_temp_dir().'/yaml_stagings/';
        $this->name = 'test';
        $this->params = array(
            'domain'       => 'rch.fr',
            'user'         => 'chalasr',
            'keys'         => '/home/ssh_user/.ssh/id_rsa',
            'forwardAgent' => 'false',
            'authMethods'  => 'publickey password',
            'deployTo'     => '/var/www/html',
        );
    }

    public function testGenerate()
    {
        $generator = new YamlStagingGenerator($this->params, $this->path, $this->name);
        $this->generateStaging($generator);

        $this->assertEquals($this->expected, file_get_contents(sprintf('%s%s.yml', $this->path, $this->name)));
    }

    private function generateStaging(GeneratorInterface $generator)
    {
        $generator->open();
        $generator->write();
        $generator->close();
    }

    public function tearDown()
    {
        unlink(sprintf('%s%s.yml', $this->path, $this->name));
        rmdir($this->path);
    }
}
