###########################################################################
#          This file is generated by Chalasdev/CapistranoBundle           #
#                                                                         #
#               https://github.com/chalasr/CapistranoBundle               #
#                  Robin Chalas <robin.chalas@gmail.com>                  #
#                                                                         #
###########################################################################
